/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "store_service.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_init_1 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (init_1_svc(result, rqstp));
}

int
_store_1 (store_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (store_1_svc(argp->sender, argp->receiver, argp->msg_id, argp->msg, argp->md5, result, rqstp));
}

int
_getnummessages_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (getnummessages_1_svc(*argp, result, rqstp));
}

int
_getmessage_1 (getmessage_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (getmessage_1_svc(argp->user, argp->msg_id, result, rqstp));
}

static void
store_service_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		store_1_argument store_1_arg;
		char *getnummessages_1_arg;
		getmessage_1_argument getmessage_1_arg;
	} argument;
	union {
		int store_1_res;
		int getnummessages_1_res;
		response getmessage_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case init:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_init_1;
		break;

	case store:
		_xdr_argument = (xdrproc_t) xdr_store_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_store_1;
		break;

	case getNumMessages:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_getnummessages_1;
		break;

	case getMessage:
		_xdr_argument = (xdrproc_t) xdr_getmessage_1_argument;
		_xdr_result = (xdrproc_t) xdr_response;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_getmessage_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!store_service_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;
	struct sockaddr_in service_addr; /* Struct to store the address of the server */

	pmap_unset (STORE_SERVICE, STORE_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, STORE_SERVICE, STORE_VERSION, store_service_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (STORE_SERVICE, STORE_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, STORE_SERVICE, STORE_VERSION, store_service_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (STORE_SERVICE, STORE_VERSION, tcp).");
		exit(1);
	}
	/* Get the machine's IP address */
	get_myaddress(&service_addr);
	char * ip = inet_ntoa(service_addr.sin_addr);
	/* If the address could not be obtained (no network connection), then print error and exit */
	if(strlen(ip) == 0){
		fprintf (stderr, "%s", "cannot get the IP address of the service.");
		exit(1);
	}
	printf("Store service running at: %s\n", ip);
	/* Self-invoke the init process when starting the server */
	init_1_svc(NULL, NULL);
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
