/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "store_service.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_1(void *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, init, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
store_1(char *sender, char *receiver, u_int msg_id, char *msg, char *md5, int *clnt_res,  CLIENT *clnt)
{
	store_1_argument arg;
	arg.sender = sender;
	arg.receiver = receiver;
	arg.msg_id = msg_id;
	arg.msg = msg;
	arg.md5 = md5;
	return (clnt_call (clnt, store, (xdrproc_t) xdr_store_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getnummessages_1(char *user, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, getNumMessages,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &user,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
getmessage_1(char *user, u_int msg_id, response *clnt_res,  CLIENT *clnt)
{
	getmessage_1_argument arg;
	arg.user = user;
	arg.msg_id = msg_id;
	return (clnt_call (clnt, getMessage, (xdrproc_t) xdr_getmessage_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_response, (caddr_t) clnt_res,
		TIMEOUT));
}
